eai:
  ui:
    api-url: http://localhost:9008 
    
eureka:
  client:
    serviceUrl:
      defaultZone:  ${eureka_service_url:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    config:
      override-system-properties: false
  datasource:
    url: jdbc:h2:mem:${MY_DB_NAME}
    username: ${MY_DB_USER}
    password:
    driver-class-name: org.h2.Driver
    test-on-borrow: true
    test-while-idle: true
    validation-interval: 600000
    validation-query: select 1 from dual
    validation-query-timeout: 1
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true    
  h2:
    console:
      enabled: true
      path: /h2 
      settings:
        web-allow-others: true     
      
listen:
  event:
    topic: true      
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG