eai:
  ui:
    api-url: http://10.1.120.2

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.120.4/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    config:
      override-system-properties: false
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        default_schema: EAI_SCHEMA
        format_sql: true
  
      
listen:
  event:
    topic: true      
