
eai:
  allowed-origins:
    - http://localhost:4200
    - http://localhost:4300
    - http://localhost:4500
    - http://localhost:80
    - http://localhost

#secret-keys
jwt:
  secret-key: ${JWT_SECRET}