eai:
  ui:
    api-url: http://localhost:9008

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    serviceUrl:
      defaultZone:  ${eureka_service_url:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    config:
      override-system-properties: false
  datasource:
    url: jdbc:mysql://${MY_DB_HOST}:${MY_DB_PORT}/${MY_DB_NAME}
    username: ${MY_DB_USER}
    password: ${MY_DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 60000
      connectionTimeout: 30000
  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        default_schema: EAI_SCHEMA
        ddl-auto: update 
listen:
  event:
    topic: true      
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG