eai:
  ui:
    api-url: http://localhost:4200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    config:
      override-system-properties: false
  datasource:
    url: jdbc:h2:mem:userDB;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS EAI_SCHEMA
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: EAI_SCHEMA
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
      
listen:
  event:
    topic: false      
