spring:
  cloud:
    config:
      override-system-properties: false

      
listen:
  event:
    topic: true  

bootstrap:
  servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

userActivity:
  kafka:
    topic: network.eai.userActivity  
    
security:
  protocol: NA

sasl:
  mechanism: NA
  jaas:
    config: NA        
