spring:
  cloud:
    config:
      override-system-properties: false
  datasource:
    url: jdbc:mysql://192.168.0.5:3306/userdb
    username: root
    password: root1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        default_schema: EAI_SCHEMA
        format_sql: true
       

bootstrap:
  servers: 192.168.0.5:9092
  
security:
  protocol: NA

sasl:
  mechanism: NA
  jaas:
    config: NA   