spring:
  cloud:
    config:
      override-system-properties: false

bootstrap:
  servers: ${MY_BOOTSTRAP_SERVER:localhost:9092}
  
security:
  protocol: NA

sasl:
  mechanism: NA
  jaas:
    config: NA   

MY_DB_HOST: localhost
MY_DB_PORT: 3306
MY_DB_NAME: userdb
MY_DB_USER: root
MY_DB_PWD: root
ACTIVE_PROFILE: local
CONTAINER_PORT: 9008
UI_APP_URL: localhost
HOST_PORT: 9008
MY_BOOTSTRAP_SERVER: 192.168.0.5:9092