spring:
  cloud:
    config:
      override-system-properties: false

bootstrap:
  servers: ${MY_BOOTSTRAP_SERVER:localhost:9092}
  
security:
  protocol: NA

sasl:
  mechanism: NA
  jaas:
    config: NA   

MY_DB_HOST: 192.168.0.5
MY_DB_PORT: 3306
JWT_SECRET: riennesertdecourir
MY_DB_NAME: userdb
MY_DB_USER: root
MY_DB_PWD: 
ACTIVE_PROFILE: dev
UI_APP_URL: 