spring:
  cloud:
    config:
      override-system-properties: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true  

userActivity:
  stomp:
    topic: /topic/message/userActivity/
  kafka:
    topic: network.eai.userActivity  
    
listen:
  event:
    topic: true       
